# Generated by Django 4.0.5 on 2022-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=3, max_digits=100)),
                ('label', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=120)),
            ],
        ),
    ]
